<?php
/**
 *
 * Discord Notifications. An extension for the phpBB Forum Software package.
 *
 * @copyright (c) 2018, Tyler Olsen, https://github.com/rootslinux
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 */

namespace roots\discordnotifications;

/**
 * Contains the core logic for formatting and sending notification message to Discord.
 * This includes common utilities, such as verifying notification configuration settings
 */
class notification_service
{
	// Maximum number of characters allowed by Discord in a message description.
	// Reference: https://discordapp.com/developers/docs/resources/channel#embed-limits
	const MAX_MESSAGE_SIZE = 2048;

	// These numbers are decimal representations of hexadecimal color codes. Notifications can
	// only select from the colors listed here.
	private static $NOTIFICATION_TYPE_COLORS = array(
		'default'	=> 11777212, // gray
		'create'	=> 2993970,  // light green
		'update'	=> 3580392,  // light blue
		'delete'	=> 15217973, // light red
		'lock'		=> 14050617, // orange
		'user'		=> 14038504, // purple
	);

	/** @var \phpbb\config\config */
	protected $config;

	/**
	 * Constructor
	 *
	 * @param \phpbb\config\config $config
	 */
	public function __construct(\phpbb\config\config $config)
	{
		$this->config = $config;
	}

	/**
	 * Check whether notifications are enabled for a certain type
	 * @param $notification_type The name of the notification type to check
	 * @return False if the global notification setting is disabled or the notification type is disabled
	 */
	public function is_notification_type_enabled($notification_type)
	{
		// First check the global extension enabled setting. We don't generate any notifications if this is disabled
		if ($this->config->get('discord_notifications_enabled') && $this->config->get($notification_type))
		{
			return true;
		}

		return false;
	}

	/**
	 * Check whether notifications of a specific type should be sent that were generated by a forum
	 * @param $notification_type The name of the notification type to check
	 * @param $forum_id The ID of the forum to check
	 * @return False if the global notification setting is disabled, the notification type is disabled, or notifications are disabled for the forum
	 */
	public function is_forum_notification_type_enabled($notification_type, $forum_id)
	{
		if ($this->is_notification_type_enabled($notification_type) == false)
		{
			return false;
		}

		// TODO: Check the forum table to see if discord notifications are enabled on it
		return true;
	}

	/**
	 * Given the ID of a valid user, returns text that contains the user name with a link to their user profile.
	 * @param $user_id The ID of the user
	 * @return Text formatted in the notation that Discord would interpret. If the user ID is invalid, an empty string is returned.
	 */
	public function generate_user_name_link($user_id)
	{
		return "";
	}

	/**
	 * Given the ID of a valid topic, returns text that contains the topic title with a link to the topic.
	 * @param $topic_id The ID of the topic
	 * @return Text formatted in the notation that Discord would interpret. If the topic ID is invalid, an empty string is returned.
	 */
	public function generate_topic_title_link($topic_id)
	{
		return "";
	}

	/**
	 * Given the ID of a valid post, returns text that contains the post title with a link to the post.
	 * @param $user_id The ID of the user
	 * @return Text formatted in the notation that Discord would interpret. If the post ID is invalid, an empty string is returned.
	 */
	public function generate_post_title_link($post_id)
	{
		return "";
	}

	/**
	 * Sends a notification message to Discord. This function checks the master switch configuration for the extension, but does
	 * no further checks. The caller is responsible for performing full validation of the notification prior to calling this function.
	 * @param message The message text to send. If empty, no message will be sent.
	 */
	public function send_discord_notification($message, $color)
	{
		if ($this->config['discord_notifications_enabled'] == 0 || $message == '')
		{
			return;
		}

		// Note that the value stored in the config table will always be a valid URL when discord_notifications_enabled is set
		$discord_webhook_url = $this->config['discord_notifications_webhook_url'];

		$this->send_message($discord_webhook_url, $message, $color);
	}

	/**
	 * Sends a notification message to Discord, disregarding any configurations that are currently set. This method is primarily for user testing
	 * purposes from the ACP
	 * @param message The message text to send. If empty, no message will be sent.
	 * @param discord_webhook_url The URL of the Discord webhook to transmit the message to. If this is an invalid URL, no message will be sent.
	 */
	public function force_send_discord_notification($message, $discord_webhook_url)
	{
		if (!filter_var($discord_webhook_url, FILTER_VALIDATE_URL) || $message == '')
		{
			return;
		}

		$this->send_message($discord_webhook_url, $message, 'default');
	}

	/**
	 * Helper function that performs the message transmission. Arguments are guaranteed to be valid strings.
	 * @param message The message text to send.
	 * @param discord_webhook_url The URL of the Discord webhook to transmit the message to.
	 * @return
	 */
	private function send_message($discord_webhook_url, $message, $color)
	{
		// First analyze the message and replace characters that would cause issues with the JSON formatting
		// Convert " to ' in the message to be sent as otherwise JSON formatting would break.
		$message = str_replace('"', "'", $message);

		// TODO: Verify that the message size is within the allowable limit and truncate if necessary

		// Fetch the requested color value. If not found, use the default color
		if (in_array($color, $NOTIFICATION_TYPE_COLORS) == true) {
			$color = $NOTIFICATION_TYPE_COLORS[$color];
		}
		else {
			$color = $NOTIFICATION_TYPE_COLORS['default'];
		}


		// Place the message inside the JSON structure that Discord expects to receive. Uses embeds for embedded rich content
		// See: https://discordapp.com/developers/docs/resources/webhook#execute-webhook
		$post = sprintf('{"embeds": [{ "color" : "%d" ,"description" : "%s"}]}', $color, $message);

		// Use CURL to transmit the message via a POST operation to the webhook URL.
		$h = curl_init();
		curl_setopt($h, CURLOPT_URL, $discord_webhook_url);
		curl_setopt($h, CURLOPT_POST, 1);
		curl_setopt($h, CURLOPT_POSTFIELDS, $post);
		// This disables SSL. Its not ideal, but we don't expect to be transmitting sensitive data anyway.
		curl_setopt ($h, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt ($h, CURLOPT_SSL_VERIFYPEER, 0);
		$response = curl_exec($h);
		curl_close($h);
	}

	private function generate_full_url($url)
	{
		// TODO: Return base URL of forum + url argument
		return $url;
	}

	/**
	 * The Discord webhook api does not accept urlencoded text. This function replaces problematic characters.
	 */
	private static function reformat_url($url)
	{
		$url = str_replace(" ", "%20", $url);
		$url = str_replace("(", "%28", $url);
		$url = str_replace(")", "%29", $url);
		return $url;
	}
}
